# Important Notes:
# Every field you add must be added to buildSrc/src/main/kotlin/multiloader-common.gradle.kts expandProps map.

# Project
version=1.2.0
group=cc.sighs.handheldmoon
java_version=25

# Common
minecraft_version=26.1
mod_name=HandheldMoon
common_mainclassname=HandheldMoon
fabric_mainclassname=HandheldMoonFabric
neoforge_mainclassname=HandheldMoonNeoForge
mod_author=MerrySnow, Flechazo, zhenshiz
mod_id=handheldmoon
license=All-Rights-Reserved
credits=
description=This mod adds several large-area lighting items such as flashlights and mini moons.
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.1+26.1
fabric_loader_version=0.18.4

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# Release Publishing
release_type=beta
# Valid values: client / server / both
release_dist=both
# Used by both Modrinth and CurseForge publishing tasks (supports multiline with \n)
release_changelog=**Individual Device Configuration**: You can now customize settings for each **Moonlight Lamp** and **Full Moon** individually. Simply press **'G'** while looking at the block entity or while holding the item in your hand to open the config screen.\n**Global Defaults**: The original settings have now become the "Global Default". Any device without a custom configuration will automatically use these global settings (I know it sounds a bit messy, but that's how it works! lol).\n**Major Performance Optimization**: Performance has been significantly improved. On my local machine, the FPS while using the flashlight is now nearly identical to when it is turned off.\n**No Backports**: Please do **not** request to port these new features back to version **1.20.1** or **1.21.1**. Those versions are no longer being maintained.\n**Beta Warning**: This version is still in **Beta**. If you encounter any bugs, please report them!
modrinth_project=pKlHQBvX
modrinth_project_fabric=
modrinth_project_neoforge=
curseforge_project=1398036
curseforge_project_fabric=
curseforge_project_neoforge=

curios_version = 15.0.0-beta.1+26.1

# Gradle
org.gradle.jvmargs=-Xmx3G -Djava.net.useSystemProxies=true
org.gradle.daemon=false

